#!/usr/bin/env bash
if [[ $OAUTH_CLIENT_ID ]] && [[ $OAUTH_CLIENT_SECRET ]] && [[ $OAUTH_TENANT_ID ]]; then

  SSMTP_TLS=${TLS_SOURCE:-YES}
  SSMTP_SERVER=${SMTP_HOSTNAME:-smtp.gmail.com}
  SSMTP_PORT=8025
  SSMTP_HOSTNAME=localhost
  SSMTP_FROM=${SSMTP_FROM:-USERNAME@HOSTNAME}

  # root=$SSMTP_TO
cat << EOF > /etc/ssmtp/ssmtp.conf
mailhub=$SSMTP_SERVER:$SSMTP_PORT
AuthUser=$SSMTP_USER
AuthPass=$SSMTP_PASS
UseSTARTTLS=$SSMTP_TLS
hostname=$SSMTP_HOSTNAME
FromLineOverride=YES
EOF

fi
